/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.Presentation;

import br.com.tcc.DataAccess.DepositoDAO;
import br.com.tcc.DataAccess.FormaDePagamentoDAO;
import br.com.tcc.DataAccess.ProdutoDAO;
import br.com.tcc.DataAccess.RetiradaDAO;
import br.com.tcc.DataAccess.VendaDAO;
import br.com.tcc.DomainModel.Deposito;
import br.com.tcc.DomainModel.FormaDePagamento;
import br.com.tcc.DomainModel.ItemVendaProduto;
import br.com.tcc.DomainModel.Retirada;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Luiza
 */
public class frmReceberPagamentoVenda extends javax.swing.JDialog {

    /**
     * Creates new form frmReceberPagamentoVenda
     */
    frmMenuPrincipal janelaPai;
    public frmReceberPagamentoVenda(java.awt.Frame parent, boolean modal, frmMenuPrincipal janelaPai) {
        super(parent, modal);
        this.janelaPai = janelaPai;
        
                
        initComponents();
         Color minhaCor = new Color(239,239,239);
        this.getContentPane().setBackground(minhaCor);
        
        calculaValorAPagar();
        carregaFormaDePagamento();
    }
    
    
    private void carregaFormaDePagamento(){
        FormaDePagamentoDAO daoFormaDePagamento = new FormaDePagamentoDAO();
        
        FormaDePagamento tmp = new FormaDePagamento();
        tmp.setNome("Selecione");
        
        cbxFormaDePagamento.removeAllItems();
        cbxFormaDePagamento.addItem(tmp);
        
        for(FormaDePagamento f: daoFormaDePagamento.ListarTodos()){
            cbxFormaDePagamento.addItem(f);
        }
    }

    
    private void calculaValorAPagar(){
      lblTotalAPagar.setText(String.valueOf(janelaPai.novaVenda.calculaValorTotal()));
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFormaDePagamento = new javax.swing.JLabel();
        cbxFormaDePagamento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCampoObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Receber Pagamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 228, 228));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pagamento");

        lblFormaDePagamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormaDePagamento.setText("Forma de Pagamento*:");

        cbxFormaDePagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxFormaDePagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFormaDePagamentoItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Total a Pagar");

        lblTotalAPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalAPagar.setForeground(new java.awt.Color(0, 0, 102));

        lblValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValor.setText("Valor*:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFormaDePagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        btnPagar.setBackground(new java.awt.Color(239, 239, 239));
        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/Presentation/icones/pagamento.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagarMouseExited(evt);
            }
        });
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(239, 239, 239));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/Presentation/icones/Fechar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCampoObrigatorio.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCampoObrigatorio.setText("*Campo Obrigatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCampoObrigatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(btnCancelar)
                        .addGap(209, 209, 209))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCampoObrigatorio)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if(Float.parseFloat(txtValor.getText()) >= (Float.parseFloat(lblTotalAPagar.getText()))){
            
            if(cbxFormaDePagamento.getSelectedIndex() ==0 ){   //se o o objeto selecionado nao for a opcao "selecione"
                txtValor.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Selecione uma Forma de Pagamento !");
                
    
             }else{
                txtValor.setEnabled(true);
                
                
                
                /*
                
                        Ver as opcoes de à prazo
                */
                
                VendaDAO daoVenda = new VendaDAO();
                janelaPai.novaVenda.setCaixa(janelaPai.caixa);
                janelaPai.novaVenda.setFormaDePagamento((FormaDePagamento) cbxFormaDePagamento.getSelectedItem());
                janelaPai.novaVenda.setValorVenda(Float.parseFloat(txtValor.getText()));
                janelaPai.novaVenda.setCliente(janelaPai.clienteCOmboVenda);

                if (daoVenda.Salvar(janelaPai.novaVenda)) {
                    
                    Deposito tmp = new Deposito();
                    DepositoDAO daoTmp = new DepositoDAO();
                    tmp.setCaixa(janelaPai.caixa);
                    tmp.setFuncionario(janelaPai.usuarioLogado.getFuncionario());
                    tmp.setValor(janelaPai.novaVenda.getValorVenda());//teste
                    tmp.setObservacao("Pagamento de venda ");

                    daoTmp.Salvar(tmp);
                    janelaPai.caixa.addDeposito(tmp);
                    /*
                        RECEBER VALOR DO TROCO E ARMAZENAR :-/
                    */
                    Retirada tmpTroco = new Retirada();
                    RetiradaDAO daoRetirada = new RetiradaDAO();
                    tmpTroco.setValor((Float.valueOf(txtValor.getText()) - janelaPai.novaVenda.calculaValorTotal()));
                    tmpTroco.setCaixa(janelaPai.caixa);
                    tmpTroco.setDescricao("Troco Referente a Venda "+ janelaPai.novaVenda.getDataHora().toString());
                    tmpTroco.setFuncionario(janelaPai.usuarioLogado.getFuncionario());
                    
                    daoRetirada.Salvar(tmpTroco);
                    janelaPai.caixa.addRetirada(tmpTroco);
                    
                    
                    JOptionPane.showMessageDialog(rootPane, "Valor do Troco R$ " +tmpTroco.getValor() );
                    
                    JOptionPane.showMessageDialog(rootPane, "Venda Salva com sucesso!");
                    
                    ProdutoDAO tmpP = new ProdutoDAO();
                    
                    for(ItemVendaProduto p :janelaPai.novaVenda.getProdutos()){
                        tmpP.AtualizarEstoqueVenda(p.getProduto(), p.getQtd());
                    }
             
                    janelaPai.desativarVenda();
                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar a venda");
                }
            }
                    
        }else{
            JOptionPane.showMessageDialog(rootPane, "O valor pago é menor que o valor da venda !");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseEntered
        Color minhaCor = new Color(115,183,253);
        this.btnPagar.setBackground(minhaCor);
    }//GEN-LAST:event_btnPagarMouseEntered

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        Color minhaCor = new Color(115,183,253);
        this.btnCancelar.setBackground(minhaCor);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseExited
        Color minhaCor = new Color(239,239,239);
        this.btnPagar.setBackground(minhaCor);
    }//GEN-LAST:event_btnPagarMouseExited

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        Color minhaCor = new Color(239,239,239);
        this.btnPagar.setBackground(minhaCor);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void cbxFormaDePagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFormaDePagamentoItemStateChanged
        if(cbxFormaDePagamento.getSelectedIndex() ==2){
                txtValor.setEnabled(false);
        }else{
            txtValor.setEnabled(true);
        }
    }//GEN-LAST:event_cbxFormaDePagamentoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox cbxFormaDePagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCampoObrigatorio;
    private javax.swing.JLabel lblFormaDePagamento;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
