/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.Presentation;

import br.com.tcc.DataAccess.DepositoDAO;
import br.com.tcc.DataAccess.FormaDePagamentoDAO;
import br.com.tcc.DataAccess.VendaDAO;
import br.com.tcc.DomainModel.Deposito;
import br.com.tcc.DomainModel.FormaDePagamento;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Luiza
 */
public class frmReceberPagamentoVenda extends javax.swing.JDialog {

    /**
     * Creates new form frmReceberPagamentoVenda
     */
    frmMenuPrincipal janelaPai;
    public frmReceberPagamentoVenda(java.awt.Frame parent, boolean modal, frmMenuPrincipal janelaPai) {
        super(parent, modal);
        this.janelaPai = janelaPai;
        
                
        initComponents();
         Color minhaCor = new Color(239,239,239);
        this.getContentPane().setBackground(minhaCor);
        
        calculaValorAPagar();
        carregaFormaDePagamento();
    }
    
    
    private void carregaFormaDePagamento(){
        FormaDePagamentoDAO daoFormaDePagamento = new FormaDePagamentoDAO();
        
        FormaDePagamento tmp = new FormaDePagamento();
        tmp.setNome("Selecione");
        
        cbxFormaDePagamento.removeAllItems();
        cbxFormaDePagamento.addItem(tmp);
        
        for(FormaDePagamento f: daoFormaDePagamento.ListarTodos()){
            cbxFormaDePagamento.addItem(f);
        }
    }

    
    private void calculaValorAPagar(){
      lblTotalAPagar.setText(String.valueOf(janelaPai.novaVenda.calculaValorTotal()));
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFormaDePagamento = new javax.swing.JLabel();
        cbxFormaDePagamento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 228, 228));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pagamento");

        lblFormaDePagamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormaDePagamento.setText("Forma de Pagamento*:");

        cbxFormaDePagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Total a Pagar");

        lblTotalAPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalAPagar.setForeground(new java.awt.Color(0, 0, 102));

        lblValor.setText("Valor*:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFormaDePagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblValor)
                        .addGap(56, 56, 56)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValor)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnPagar)
                        .addGap(89, 89, 89)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if(Float.parseFloat(txtValor.getText()) >= (Float.parseFloat(lblTotalAPagar.getText()))){
            
            if(cbxFormaDePagamento.getSelectedIndex() != 0){   //se o o objeto selecionado nao for a opcao "selecione"
            
                /*
                
                        Ver as opcoes de à prazo
                */
                
                VendaDAO daoVenda = new VendaDAO();
                janelaPai.novaVenda.setCaixa(janelaPai.caixa);
                janelaPai.novaVenda.setFormaDePagamento((FormaDePagamento) cbxFormaDePagamento.getSelectedItem());
                janelaPai.novaVenda.setValorVenda(Float.parseFloat(txtValor.getText()));
                janelaPai.novaVenda.setCliente(janelaPai.clienteCOmboVenda);

                if (daoVenda.Salvar(janelaPai.novaVenda)) {
                    
                    Deposito tmp = new Deposito();
                    DepositoDAO daoTmp = new DepositoDAO();
                    tmp.setCaixa(janelaPai.caixa);
                    tmp.setFuncionario(janelaPai.usuarioLogado.getFuncionario());
                    tmp.setValor(janelaPai.novaVenda.getValorVenda());//teste
                    tmp.setObservacao("Pagamento de venda ");

                    daoTmp.Salvar(tmp);
                    janelaPai.caixa.addDeposito(tmp);
                    
                    
                    
                    JOptionPane.showMessageDialog(rootPane, "Valor do Troco " + (Float.valueOf(txtValor.getText()) - janelaPai.novaVenda.calculaValorTotal()));
                    
                    JOptionPane.showMessageDialog(rootPane, "Venda Salva com sucesso!");
                    
             
                    janelaPai.desativarVenda();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar a venda");
                }
    
            }
                    
        }else{
            JOptionPane.showMessageDialog(rootPane, "O valor pago é menor que o valor da venda !");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox cbxFormaDePagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFormaDePagamento;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
